# Generated by Django 6.0.3 on 2026-03-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospaciente',
            name='contato_emergencia',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
