# Generated by Django 6.0.3 on 2026-03-09 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_app', '0002_alter_dadospaciente_contato_emergencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(choices=[('M', 'Médico'), ('E', 'Enfermeiro'), ('T', 'Técnico de Enfermagem'), ('R', 'Recepcionista'), ('A', 'Administrador')], max_length=1)),
                ('especialidade', models.CharField(choices=[('CG', 'Clínico Geral'), ('CD', 'Cardiologia'), ('PD', 'Pediatria'), ('OR', 'Ortopedia'), ('NE', 'Neurologia'), ('GO', 'Ginecologia'), ('DE', 'Dermatologia')], max_length=2)),
                ('crm', models.CharField(max_length=10)),
                ('data_contratacao', models.DateField()),
                ('turno', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Dados dos Medicos',
            },
        ),
        migrations.AlterModelOptions(
            name='dadospaciente',
            options={'verbose_name_plural': 'Dados dos Pacientes'},
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('hora_consulta', models.TimeField()),
                ('motivo_consulta', models.CharField(max_length=300)),
                ('relatorio', models.TextField()),
                ('status_consulta', models.CharField(choices=[('R', 'Revogada'), ('P', 'Pendente'), ('C', 'Concluída')], max_length=1)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_app.dadospaciente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_app.dadosmedico')),
            ],
        ),
    ]
